module ToolConf
  ROBOT_POINTS = 30
  BLOCK_POINTS = 50
  BOMB_POINTS = 30
  MAX_QUANTITY = 10
end

module LandConf
  TOP_LEVEL = 3
end

module GiftConf
  BONUS_MONEY = 2000
  BONUS_POINTS = 200
  TURN_WITH_MASCOT = 5
end

module PrisonConf
  PAUSED_TURNS = 2
end

module MapConf
  FIRST_DISTRICT_LANDS_NUM = 13
  FIRST_DISTRICT_LANDS_PRICE = 200

  SECOND_DISTRICT_LANDS_NUM = 13
  SECOND_DISTRICT_LANDS_PRICE = 200

  THIRD_DISTRICT_LANDS_NUM = 6
  THIRD_DISTRICT_LANDS_PRICE = 500

  FOURTH_DISTRICT_LANDS_NUM = 13
  FOURTH_DISTRICT_LANDS_PRICE = 300

  FIFTH_DISTRICT_LANDS_NUM = 13
  FIFTH_DISTRICT_LANDS_PRICE = 300

end
